abbr g git
abbr gs  "git status"
abbr ga  "git add"
abbr gc  "git commit -v"
abbr gcm "git commit -m"
abbr gco "git checkout"
abbr gsw "git switch"
abbr gb  "git branch"
abbr gl  "git pull"
abbr gp  "git push"
abbr gst "git stash"
abbr gd  "git diff"
abbr gds "git diff --staged"
abbr glog  "git log --oneline --graph --decorate"
abbr gloga "git log --oneline --graph --decorate --all"
abbr gfa "git fetch --all --prune"
abbr grv "git remote -v"
abbr gcl "git clone"
abbr grs "git restore"
abbr grss "git restore --staged"
abbr gm  "git merge"
abbr grb "git rebase"
abbr gcp "git cherry-pick"
abbr gbl "git blame"
