abbr sc  "systemctl"
abbr scs "systemctl status"
abbr scst "sudo systemctl start"
abbr scsp "sudo systemctl stop"
abbr scr  "sudo systemctl restart"
abbr sce  "sudo systemctl enable"
abbr scd  "sudo systemctl disable"
abbr scrl "sudo systemctl reload"
abbr scdr "sudo systemctl daemon-reload"
abbr scen "sudo systemctl enable --now"
abbr scdis "sudo systemctl disable --now"

abbr jc  "journalctl"
abbr jcf "journalctl -f"
abbr jcu "journalctl -u"
abbr jcfu "journalctl -fu"
abbr jcx "journalctl -xe"
abbr jcn "journalctl -n 50"
abbr jcb "journalctl -b"
