#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
. "$HOME/.xprofile"
fi


# start dwm
dbus-update-activation-environment --all
exec dbus-launch ssh-agent --sh-syntax --exit-with-session dwm
