# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=haswell -mtune=haswell -O2 -pipe -fstack-protector-strong
-fno-plt -fno-semantic-interposition --param=l1-cache-line-size=64
--param=l1-cache-size=32 --param=l2-cache-size=3072"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="-C target-cpu=native"

PORTAGE_SCHEDULING_POLICY="idle"

NUM_CORES=2
# MAKEOPTS="-j${NUM_CORES} -l${NUM_CORES}"
MAKEOPTS="-j2 -l2"
# EMERGE_DEFAULT_OPTS="--jobs=${NUM_CORES} --load-average=${NUM_CORES} --with-bdeps=y --quiet-build --keep-going --usepkg --getbinpkg"
EMERGE_DEFAULT_OPTS="--jobs=2 --load-average=2 --with-bdeps=y --quiet-build --keep-going --usepkg --getbinpkg"

# 二进制包功能
FEATURES="buildpkg binpkg-multi-instance ccache splitdebug compressdebug parallel-install userfetch userpriv clean-logs candy getbinpkg usersandbox parallel-fetch candy ccache"

# FEATURES="${FEATURES} getbinpkg binpkg-request-signature ccache splitdebug"

USE="networkmanager pulseaudio pipewire modules-sign savedconfig wayland"
MODULES_SIGN_KEY="/root/kernel_key.pem"
#MODULES_SIGN_CERT="/root/kernel_key.pem" # Only required if the MODULES_SIGN_KEY does not also contain the certificate, try to cat /path/to/kernel_key.pem
MODULES_SIGN_HASH="sha512" # Defaults to sha512
GENTOO_MIRRORS="
http://mirrors.tuna.tsinghua.edu.cn/gentoo/
"

#L10N="en"
#LINGUAS="en"

L10N="en-US zh-CN en zh"
LINGUAS="en_US zh_CN en zh"
INPUT_DEVICES="libinput synaptics"
#PORTAGE_TMPDIR="/tmp"
PORTAGE_TMPDIR="/var/tmp/portage"
# AUTO_CLEAN="yes"

ACCEPT_LICENSE="*"
ACCEPT_KEYWORDS="~amd64"

#INPUT_DEVICES="libinput synaptics"

PORT_LOGDIR="/var/log/portage"
PORTAGE_ELOG_SYSTEM="save_summary:log,warn,error,qa echo"
PORTAGE_ELOG_CLASSES="info warn error log qa"
GRUB_PLATFORMS="efi-64"
# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
QEMU_SOFTMMU_TARGETS="x86_64"
QEMU_USER_TARGETS="x86_64"
