# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                 Decorations Configuration                     ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

decoration {
    active_opacity = 10
    rounding = 0

    blur {
        enabled = true
        size = 10
        passes = 2
        xray = true
    }

    shadow {
        enabled = false
    }
}
