# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Misc Configuration                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# https://wiki.hyprland.org/Configuring/Variables/#misc

misc {
    # 字体设置
    font_family = "Fira Sans"
    splash_font_family = "Fira Sans"
    
    # 启动画面
    disable_hyprland_logo = true
    disable_splash_rendering = true
    
    # 电源管理
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    
    # 渲染设置
    vfr = true
    vrr = 2
    force_default_wallpaper = -1
    
    # 窗口管理
    # focus_on_activate = true
    #no_direct_scanout = false
    
    # 窗口吞噬（swallow）
    enable_swallow = true
    swallow_regex = ^(nautilus|nemo|thunar|btrfs-assistant.)$
    #swallow_transition = true
    
    # 动画设置
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    
    # 窗口位置
    #new_window_center_on_cursor = false
    #new_window_center_on_monitor = false
    
    # 其他
    disable_autoreload = false
}

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                  Dwindle Configuration                       ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# https://wiki.hyprland.org/Configuring/Variables/#dwindle

dwindle {
    # 特殊工作区缩放
    special_scale_factor = 0.8
    
    # 伪平铺
    pseudotile = true
    
    # 保留分割
    preserve_split = true
    
    # 智能分割
    smart_split = false
    smart_resizing = true
    
    # 使用活动区域
    use_active_for_splits = true
}
