# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                  Monitor Configuration                        ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

monitor = , preferred, auto, 1

# XWayland scaling
xwayland {
    force_zero_scaling = true
}

# Cursor
exec = hyprctl setcursor Bibata-Modern-Classic 24
env = XCURSOR_SIZE,24

# Electron apps
env = ELECTRON_OZONE_PLATFORM_HINT, auto
