# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                  Variables Configuration                      ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
# https://wiki.hyprland.org/Configuring/Variables/#general

# General settings
general {
    # 窗口间距
    gaps_in = 3
    gaps_out = 5
    
    # 边框设置
    border_size = 3
    col.active_border = 0xfff5c2e7
    col.inactive_border = 0xff45475a
    layout = master
    
    # 浮动窗口无边框
    no_border_on_floating = false
    
    # 边框调整
    resize_on_border = true
    extend_border_grab_area = 15
    hover_icon_on_border = true
    
    # 窗口吸附
    snap {
        enabled = true
    }
}

# Group settings
group {
    groupbar {
        font_family = "Fira Sans"
    }
}

# Render settings
render {
    direct_scanout = true
}

# Master layout
master {
    new_status = master
    special_scale_factor = 0.8
}

# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Gestures                                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

gesture = 4, horizontal, workspace
gesture = 3, down, close
gesture = 3, up, fullscreen
gesture = 3, left, float
